language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
branches:
  only:
    - master
install:
  - pip install -U pip
  - python setup.py install
  - pip install -r requirements.txt
before_script:
  - black ./rds
  - pyflakes ./rds
script:
  - pytest
after_success:
  - coveralls
