language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -U pip
  - python setup.py install
  - pip install pytest
  - pip install pyflakes
  - pip install coveralls
  - if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then pip install black
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then black ./rds
  - pyflakes ./rds
script:
  - pytest
after_success:
  - coveralls
